# Genera article-anon.tex a partir de article.tex para la revision a doble ciego
# que pide JSDSE. Se vuelve a ejecutar despues de cada cambio en el manuscrito:
#
#     cd paper/jsdse && perl anonymise.pl
#
# No editar article-anon.tex a mano: se sobrescribe.
use strict; use warnings; use utf8;
binmode(STDOUT, ':encoding(UTF-8)');

my ($src, $dst) = ('article.tex', 'article-anon.tex');
local $/;
open(my $h, '<:encoding(UTF-8)', $src) or die "$src: $!";
my $d = <$h>; close $h;

my @hecho;

# 1. Autoria y adscripcion.
$d =~ s/\x5cauthor\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}/\x5cauthor{}/s
  and push @hecho, 'bloque de autor vaciado';

# 2. Agradecimientos: el manuscrito no los lleva, asi que esta regla no hace
#    nada hoy. Se queda como red: si alguna vez se anaden, delatarian la
#    institucion y la version anonima saldria con ellos.
$d =~ s/%% -{10,}\n\x5csection\*\{Acknowledgments\}\n.*?(?=\x5csection\*\{Declaration of Interest)//s
  and push @hecho, 'agradecimientos eliminados';

# 3. Disponibilidad del software. Sustituir URL por URL dejaba una frase
#    ridicula —"el identificador [anonimizado] resuelve a la ultima version"—,
#    asi que se reescribe el parrafo entero. Lo que el revisor necesita saber
#    es la licencia y que la version descrita esta fijada; el numero de version
#    se conserva porque no identifica a nadie.
my $anon = <<'PARRAFO';
PCAPro is free software distributed under the GNU General Public License,
version 3 or later. The source code, documentation and teaching materials are
available in a public repository and archived in a general-purpose research
data repository with a persistent identifier; both are anonymised for review.
The archived deposit is pinned to version 1.0.1, the version described in this
article. A working installation requiring no download is also available and
runs the current release, which may be ahead of the version described here.
PARRAFO
my $n = 0;
$n += ($d =~ s{PCAPro is free software distributed under the GNU General Public License,.*?ahead of the version described here\.\n}{$anon}s);
# Red de seguridad: cualquier URL que aparezca fuera de ese parrafo.
$n += ($d =~ s{\x5curl\{https://github\.com/\S+?\}}{[repository, anonymised for review]}g);
$n += ($d =~ s{\x5curl\{https://doi\.org/10\.5281/zenodo\.\d+\}}{[archived deposit, anonymised for review]}g);
$n += ($d =~ s{\x5curl\{https://\S+?\.github\.io/\S*?\}}{[working installation, anonymised for review]}g);
push @hecho, "$n sustituciones de disponibilidad" if $n;

# 4. El recordatorio de anonimizar ya no aplica en el fichero generado.
$d =~ s/%% TODO: in the anonymous version.*?identify the author\.\n\n//s
  and push @hecho, 'recordatorio obsoleto retirado';

# 5. Cabecera: que quede claro cual de las dos versiones es esta.
$d =~ s/%% NON-ANONYMOUS VERSION\..*?%% Both versions must be submitted together\.\n/%% ANONYMOUS VERSION, generated by anonymise.pl. Do not edit by hand: edit\n%% article.tex and run the script again. Submitted together with the\n%% non-anonymous version, as JSDSE requires.\n/s
  and push @hecho, 'cabecera actualizada';

open(my $o, '>:encoding(UTF-8)', $dst) or die "$dst: $!";
print $o $d; close $o;

print "$dst generado\n";
print "  - $_\n" for @hecho;

# 6. Comprobacion: nada de lo que identifica al autor puede sobrevivir.
my @fugas;
for my $p ('Barrera', 'Guzm', 'Chapingo', 'Huatusco', 'chapingo\.mx',
           'luisangelbg', 'lbarrerag', 'zenodo\.\d', 'github\.com', 'orcid') {
  push @fugas, $p if $d =~ /$p/i;
}
if (@fugas) { print "\nFUGAS QUE SIGUEN EN EL TEXTO: @fugas\n"; exit 1; }
print "\nsin rastros literales del autor\n";

print <<'NOTA';

Queda un limite que ningun marcador arregla: el nombre PCAPro aparece en el
titulo y en todo el texto, y buscarlo lleva al repositorio publico y de ahi al
autor. Renombrar el software haria ilegible el articulo. Es la situacion normal
de un articulo de software ya publicado que se manda a revision a doble ciego;
lo honesto es declararlo en la carta al editor y dejar que la revista decida.
NOTA
