# Genera article-anon.tex a partir de article.tex para la revision a doble ciego
# que pide JSDSE. Se vuelve a ejecutar despues de cada cambio en el manuscrito:
#
#     cd paper/jsdse && perl anonymise.pl
#
# No editar article-anon.tex a mano: se sobrescribe.
use strict; use warnings; use utf8;
binmode(STDOUT, ':encoding(UTF-8)');

my ($src, $dst) = ('article.tex', 'article-anon.tex');
local $/;
open(my $h, '<:encoding(UTF-8)', $src) or die "$src: $!";
my $d = <$h>; close $h;

my @hecho;

# 1. Autoria y adscripcion.
$d =~ s/\x5cauthor\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}/\x5cauthor{}/s
  and push @hecho, 'bloque de autor vaciado';

# 2. Agradecimientos: el manuscrito no los lleva, asi que esta regla no hace
#    nada hoy. Se queda como red: si alguna vez se anaden, delatarian la
#    institucion y la version anonima saldria con ellos.
$d =~ s/%% -{10,}\n\x5csection\*\{Acknowledgments\}\n.*?(?=\x5csection\*\{Declaration of Interest)//s
  and push @hecho, 'agradecimientos eliminados';

# 3. Las tres URL llevan el usuario de GitHub y el DOI, que resuelve al nombre.
my $n = 0;
$n += ($d =~ s{\x5curl\{https://github\.com/\S+?\}}{[repository, anonymised for review]}g);
$n += ($d =~ s{\x5curl\{https://doi\.org/10\.5281/zenodo\.\d+\}}{[archived deposit, anonymised for review]}g);
$n += ($d =~ s{\x5curl\{https://\S+?\.github\.io/\S*?\}}{[working installation, anonymised for review]}g);
push @hecho, "$n enlaces sustituidos" if $n;

# 4. El recordatorio de anonimizar ya no aplica en el fichero generado.
$d =~ s/%% TODO: in the anonymous version.*?identify the author\.\n\n//s
  and push @hecho, 'recordatorio obsoleto retirado';

# 5. Cabecera: que quede claro cual de las dos versiones es esta.
$d =~ s/%% NON-ANONYMOUS VERSION\..*?%% Both versions must be submitted together\.\n/%% ANONYMOUS VERSION, generated by anonymise.pl. Do not edit by hand: edit\n%% article.tex and run the script again. Submitted together with the\n%% non-anonymous version, as JSDSE requires.\n/s
  and push @hecho, 'cabecera actualizada';

open(my $o, '>:encoding(UTF-8)', $dst) or die "$dst: $!";
print $o $d; close $o;

print "$dst generado\n";
print "  - $_\n" for @hecho;

# 6. Comprobacion: nada de lo que identifica al autor puede sobrevivir.
my @fugas;
for my $p ('Barrera', 'Guzm', 'Chapingo', 'Huatusco', 'chapingo\.mx',
           'luisangelbg', 'lbarrerag', 'zenodo\.\d', 'github\.com', 'orcid') {
  push @fugas, $p if $d =~ /$p/i;
}
if (@fugas) { print "\nFUGAS QUE SIGUEN EN EL TEXTO: @fugas\n"; exit 1; }
print "\nsin rastros literales del autor\n";

print <<'NOTA';

Queda un limite que ningun marcador arregla: el nombre PCAPro aparece en el
titulo y en todo el texto, y buscarlo lleva al repositorio publico y de ahi al
autor. Renombrar el software haria ilegible el articulo. Es la situacion normal
de un articulo de software ya publicado que se manda a revision a doble ciego;
lo honesto es declararlo en la carta al editor y dejar que la revista decida.
NOTA
